/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbmcourseenrollmentsystem;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahan Buddhika
 */
public class PostergraduateStudentsCourseUpdate extends javax.swing.JFrame {
    DBOperation DBop = new DBOperation();
    /**
     * Creates new form PostergraduateStudentsCourseUpdate
     */
    public PostergraduateStudentsCourseUpdate() {
        initComponents();
    }
    
    void setFields(PostergraduateStudentsCourseRegDetails std){//when click update load the db items to the grid
            txtstudentid.setText(std.getStudentID());
            ddfaculty.setSelectedItem(std.getFaculty());
            ddyearofregistration.setSelectedItem(new Integer(std.getYearOfReg()).toString());
            ddcourseid.setSelectedItem(std.getCourseID());
            txtm1.setText(std.getMainsub1());
            txtm2.setText(std.getMainsub2());
            ddsubject1.setSelectedItem(std.getChoosesub1());
            ddsubject2.setSelectedItem(std.getChoosesub2());
            ddsubject3.setSelectedItem(std.getChoosesub3());
            ddsubject4.setSelectedItem(std.getChoosesub4());
            txtsubc1.setText(std.getMainsubID1());
            txtsubc2.setText(std.getMainsubID2());
            txtsubc3.setText(std.getChoosesubID1());
            txtsubc4.setText(std.getChoosesubID2());
            txtsubc5.setText(std.getChoosesubID3());
            txtsubc6.setText(std.getChoosesubID4());
            txtp1.setText(new Integer(std.getMainsub1Payment()).toString());
            txtp2.setText(new Integer(std.getMainsub2Payment()).toString());
            txtp3.setText(new Integer(std.getChoosesub1Payment()).toString());
            txtp4.setText(new Integer(std.getChoosesub2Payment()).toString());
            txtp5.setText(new Integer(std.getChoosesub3Payment()).toString());
            txtp6.setText(new Integer(std.getChoosesub4Payment()).toString());
            
        }

    public void clearFeilds(){
                txtm1.setText("");
                txtm2.setText("");
                ddsubject1.setToolTipText("");
                ddsubject2.setToolTipText("");
                ddsubject3.setToolTipText("");
                ddsubject4.setToolTipText("");
                txtsubc1.setText("");
                txtsubc2.setText("");
                txtsubc3.setText("");
                txtsubc4.setText("");
                txtsubc5.setText("");
                txtsubc6.setText("");
                txtp1.setText("");
                txtp2.setText("");
                txtp3.setText("");
                txtp4.setText("");
                txtp5.setText("");
                txtp6.setText("");
                ddfaculty.setToolTipText("");
                ddyearofregistration.setToolTipText("");
                ddcourseid.setToolTipText("");
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ddcourseid = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ddsubject1 = new javax.swing.JComboBox<>();
        ddsubject2 = new javax.swing.JComboBox<>();
        ddsubject3 = new javax.swing.JComboBox<>();
        ddsubject4 = new javax.swing.JComboBox<>();
        btnproceed = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        ddyearofregistration = new javax.swing.JComboBox<>();
        ddfaculty = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtp3 = new javax.swing.JTextField();
        txtp4 = new javax.swing.JTextField();
        txtp5 = new javax.swing.JTextField();
        txtp6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtm1 = new javax.swing.JTextField();
        txtm2 = new javax.swing.JTextField();
        txtsubc1 = new javax.swing.JTextField();
        txtsubc2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtp1 = new javax.swing.JTextField();
        txtp2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtsubc3 = new javax.swing.JTextField();
        txtsubc4 = new javax.swing.JTextField();
        txtsubc5 = new javax.swing.JTextField();
        txtsubc6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Courses Update");

        jLabel2.setText("Student ID");

        txtstudentid.setEditable(false);

        jLabel3.setText("Faculty");

        jLabel4.setText("Year Of Registration");

        jLabel5.setText("Course ID");

        ddcourseid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddcourseidItemStateChanged(evt);
            }
        });
        ddcourseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddcourseidActionPerformed(evt);
            }
        });

        jLabel6.setText("Subject 1");

        jLabel7.setText("Subject 2");

        jLabel8.setText("Subject 3");

        jLabel9.setText("Subject 4");

        btnproceed.setText("PROCEED");
        btnproceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproceedActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        ddyearofregistration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Registration Year", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024.2025" }));

        ddfaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Faculty", "School Of Computing", "School Of Business", "School Of Enginearing" }));
        ddfaculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddfacultyItemStateChanged(evt);
            }
        });
        ddfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddfacultyActionPerformed(evt);
            }
        });

        jLabel10.setText("Payment");

        jLabel11.setText("Payment");

        jLabel12.setText("Payment");

        jLabel13.setText("Payment");

        txtp3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2), "Main Subjects"));

        txtm1.setEditable(false);

        txtm2.setEditable(false);

        txtsubc1.setEditable(false);

        txtsubc2.setEditable(false);
        txtsubc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubc2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Payment");

        jLabel16.setText("Payment");

        txtp1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtp2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsubc1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(txtsubc2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtm2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtp2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtm1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtp1))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsubc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel14.setText("Main Subjects");

        txtsubc3.setEditable(false);

        txtsubc4.setEditable(false);

        txtsubc5.setEditable(false);

        txtsubc6.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Postergraduate Student's");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(btnproceed, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(txtsubc4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(262, 262, 262)
                                                .addComponent(jLabel11))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtsubc3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ddsubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtsubc6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtsubc5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ddsubject3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ddsubject4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ddsubject2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtp3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(txtp4)
                                    .addComponent(txtp5)
                                    .addComponent(txtp6))
                                .addGap(10, 10, 10)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ddcourseid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ddyearofregistration, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ddfaculty, javax.swing.GroupLayout.Alignment.LEADING, 0, 426, Short.MAX_VALUE)
                                            .addComponent(txtstudentid, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ddfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ddyearofregistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddcourseid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ddsubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ddsubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ddsubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ddsubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproceed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String[] getCourseID(String reg) {
        String[] course = new String[30];
        if (reg.equalsIgnoreCase("School Of Computing")) {
            course[0] = "PC11";
            course[1] = "PC12";
            course[2] = "PC21";
            course[3] = "PC22";
            course[4] = "PC31";
            course[5] = "PC32";
            course[6] = "PC41";
            course[7] = "PC42";
        } else if (reg.equalsIgnoreCase("School Of Business")) {
            course[0] = "PB11";
            course[1] = "PB12";
            course[2] = "PB21";
            course[3] = "PB22";
            course[4] = "PB31";
            course[5] = "PB32";
            course[6] = "PB41";
            course[7] = "PB42";
        } else if (reg.equalsIgnoreCase("School Of Enginearing")) {
            course[0] = "PE11";
            course[1] = "PE12";
            course[2] = "PE21";
            course[3] = "PE22";
            course[4] = "PE31";
            course[5] = "PE32";
            course[6] = "PE41";
            course[7] = "PE42";
        }
        return course;

    }
     
     
     
      public String[] getPostergraduateCourse1(String reg) {
        String[] postergraduate = new String[30];
        if (reg.equalsIgnoreCase("PC11")) {
            postergraduate[0] = "ICT Tools";
            postergraduate[1] = "Computer Architecture";
            postergraduate[2] = "Communication Skills";
            postergraduate[3] = "Java";
            postergraduate[4] = "Python";
        }else if(reg.equalsIgnoreCase("PC12")){
            postergraduate[0] = "Data Structure & Algorithms";
            postergraduate[1] = "Artificial Intelligence";
            postergraduate[2] = "Computer Security";
            postergraduate[3] = "Mathamatical method";
            postergraduate[4] = "Statistic";
        }else if(reg.equalsIgnoreCase("PC21")){
            postergraduate[0] = "Compiler Design";
            postergraduate[1] = "Cloud Computing";
            postergraduate[2] = "Real Time Systems";
            postergraduate[3] = "Cysber Security";
            postergraduate[4] = "Computer Security";
        }else if(reg.equalsIgnoreCase("PC22")){
            postergraduate[0] = "Web Design";
            postergraduate[1] = "Mahine Learning";
            postergraduate[2] = "Modern Database";
            postergraduate[3] = "Wireless Sensor Network";
            postergraduate[4] = "Data Mining";
        }else if(reg.equalsIgnoreCase("PC31")){
            postergraduate[0] = "Software Testing";
            postergraduate[1] = "Wireless Sensor Network";
            postergraduate[2] = "Data Mining";
            postergraduate[3] = "Web Design";
            postergraduate[4] = "Mahine Learning";
        }else if(reg.equalsIgnoreCase("PC32")){
            postergraduate[0] = "Distributed Systems";
            postergraduate[1] = "Cysber Security";
            postergraduate[2] = "Computer Security";
            postergraduate[3] = "Compiler Design";
            postergraduate[4] = "Cloud Computing";
        }else if(reg.equalsIgnoreCase("UC41")){
            postergraduate[0] = "Research Methodology";
            postergraduate[1] = "Mathamatical method";
            postergraduate[2] = "Statistic";
            postergraduate[3] = "ICT Tools";
            postergraduate[4] = "Computer Architecture";
        }else if(reg.equalsIgnoreCase("PC42")){
            postergraduate[0] = "Discrete Maths";
            postergraduate[1] = "Java";
            postergraduate[2] = "Python";
            postergraduate[3] = "Artificial Intelligence";
            postergraduate[4] = "Computer Security";
        }else if(reg.equalsIgnoreCase("PB11")){
            postergraduate[0] = "Business Law";
            postergraduate[1] = "Economics";
            postergraduate[2] = "Ethics";
            postergraduate[3] = "Strategic Thinking";
            postergraduate[4] = "Labour Economics";
        }else if(reg.equalsIgnoreCase("PB12")){
            postergraduate[0] = "Finance";
            postergraduate[1] = "Human Resource Management";
            postergraduate[2] = "Marketing";
            postergraduate[3] = "Foundation Of Marcketing";
            postergraduate[4] = "Managerial Skills";
        }else if(reg.equalsIgnoreCase("PB21")){
            postergraduate[0] = "Management resource Management";
            postergraduate[1] = "Operation Management";
            postergraduate[2] = "Organizational Behaviour";
            postergraduate[3] = "Organizational Behaviour";
            postergraduate[4] = "Business Policy";
        }else if(reg.equalsIgnoreCase("PB22")){
            postergraduate[0] = "Project Management";
            postergraduate[1] = "Stregic management";
            postergraduate[2] = "International Business";
            postergraduate[3] = "Supply chain management";
            postergraduate[4] = "Project Work";
        }else if(reg.equalsIgnoreCase("PB31")){
            postergraduate[0] = "Environment Studies";
            postergraduate[1] = "Supply chain management";
            postergraduate[2] = "Project Work";
            postergraduate[3] = "Business Law";
            postergraduate[4] = "Economics";
        }else if(reg.equalsIgnoreCase("pB32")){
            postergraduate[0] = "Microeconomics";
            postergraduate[1] = "Organizational Behaviour";
            postergraduate[2] = "Business Policy";
            postergraduate[3] = "Finance";
            postergraduate[4] = "Human Resource Management";
        }else if(reg.equalsIgnoreCase("PB41")){
            postergraduate[0] = "Business Research";
            postergraduate[1] = "Foundation Of Marcketing";
            postergraduate[2] = "Managerial Skills";
            postergraduate[3] = "Management resource Management";
            postergraduate[4] = "Operation Management";
        }else if(reg.equalsIgnoreCase("PB42")){
            postergraduate[0] = "Online Advertising";
            postergraduate[1] = "Strategic Thinking";
            postergraduate[2] = "Labour Economics";
            postergraduate[3] = "Project Management";
            postergraduate[4] = "Stregic management";
        }else if(reg.equalsIgnoreCase("PE11")){
            postergraduate[0] = "Physics";
            postergraduate[1] = "Computer Programming";
            postergraduate[2] = "Calcules";
            postergraduate[3] = "Control Enginearing";
            postergraduate[4] = "Electrical Enginearing";
        }else if(reg.equalsIgnoreCase("PE12")){
            postergraduate[0] = "Enginearing Graphics";
            postergraduate[1] = "Differential Equations";
            postergraduate[2] = "Kinematics";
            postergraduate[3] = "Plant Design";
            postergraduate[4] = "Drafting";
        }else if(reg.equalsIgnoreCase("PE21")){
            postergraduate[0] = "Chemistry";
            postergraduate[1] = "English Communication";
            postergraduate[2] = "Linear Algebra";
            postergraduate[3] = "Fluid Mechanics";
            postergraduate[4] = "Electronics";
        }else if(reg.equalsIgnoreCase("PE22")){
            postergraduate[0] = "Ethics & Value";
            postergraduate[1] = "Economics For Engineers";
            postergraduate[2] = "Kinematics";
            postergraduate[3] = "Heat And Mass";
            postergraduate[4] = "Computer Aided Design";
        }else if(reg.equalsIgnoreCase("PE31")){
            postergraduate[0] = "Material Technology";
            postergraduate[1] = "Fluid Mechanics";
            postergraduate[2] = "Electronics";
            postergraduate[3] = "Physics";
            postergraduate[4] = "Computer Programming";
        }else if(reg.equalsIgnoreCase("PE32")){
            postergraduate[0] = "Control Enginearing";
            postergraduate[1] = "Heat And Mass";
            postergraduate[2] = "Computer Aided Design";
            postergraduate[3] = "Enginearing Graphics";
            postergraduate[4] = "Differential Equations";
        }else if(reg.equalsIgnoreCase("PE41")){
            postergraduate[0] = "Chemical reactions";
            postergraduate[1] = "Plant Design";
            postergraduate[2] = "Drafting";
            postergraduate[3] = "Chemistry";
            postergraduate[4] = "English Communication";
        }else if(reg.equalsIgnoreCase("PE42")){
            postergraduate[0] = "Robotics";
            postergraduate[1] = "Control Enginearing";
            postergraduate[2] = "Electrical Enginearing";
            postergraduate[3] = "Enginearing Graphics";
            postergraduate[4] = "Differential Equations";
        }
        
        return postergraduate;
    }
     
     
     
     public String[] getPostergraduateCourse2(String reg) {
        String[] postergraduate = new String[30];
        if (reg.equalsIgnoreCase("PC11")) {
            postergraduate[0] = "ICT Tools";
            postergraduate[1] = "Computer Architecture";
            postergraduate[2] = "Communication Skills";
            postergraduate[3] = "Java";
            postergraduate[4] = "Python";
        }else if(reg.equalsIgnoreCase("PC12")){
            postergraduate[0] = "Data Structure & Algorithms";
            postergraduate[1] = "Artificial Intelligence";
            postergraduate[2] = "Computer Security";
            postergraduate[3] = "Mathamatical method";
            postergraduate[4] = "Statistic";
        }else if(reg.equalsIgnoreCase("PC21")){
            postergraduate[0] = "Compiler Design";
            postergraduate[1] = "Cloud Computing";
            postergraduate[2] = "Real Time Systems";
            postergraduate[3] = "Cysber Security";
            postergraduate[4] = "Computer Security";
        }else if(reg.equalsIgnoreCase("PC22")){
            postergraduate[0] = "Web Design";
            postergraduate[1] = "Mahine Learning";
            postergraduate[2] = "Modern Database";
            postergraduate[3] = "Wireless Sensor Network";
            postergraduate[4] = "Data Mining";
        }else if(reg.equalsIgnoreCase("PC31")){
            postergraduate[0] = "Software Testing";
            postergraduate[1] = "Wireless Sensor Network";
            postergraduate[2] = "Data Mining";
            postergraduate[3] = "Web Design";
            postergraduate[4] = "Mahine Learning";
        }else if(reg.equalsIgnoreCase("PC32")){
            postergraduate[0] = "Distributed Systems";
            postergraduate[1] = "Cysber Security";
            postergraduate[2] = "Computer Security";
            postergraduate[3] = "Compiler Design";
            postergraduate[4] = "Cloud Computing";
        }else if(reg.equalsIgnoreCase("PC41")){
            postergraduate[0] = "Research Methodology";
            postergraduate[1] = "Mathamatical method";
            postergraduate[2] = "Statistic";
            postergraduate[3] = "ICT Tools";
            postergraduate[4] = "Computer Architecture";
        }else if(reg.equalsIgnoreCase("PC42")){
            postergraduate[0] = "Discrete Maths";
            postergraduate[1] = "Java";
            postergraduate[2] = "Python";
            postergraduate[3] = "Artificial Intelligence";
            postergraduate[4] = "Computer Security";
        }else if(reg.equalsIgnoreCase("PB11")){
            postergraduate[0] = "Business Law";
            postergraduate[1] = "Economics";
            postergraduate[2] = "Ethics";
            postergraduate[3] = "Strategic Thinking";
            postergraduate[4] = "Labour Economics";
        }else if(reg.equalsIgnoreCase("PB12")){
            postergraduate[0] = "Finance";
            postergraduate[1] = "Human Resource Management";
            postergraduate[2] = "Marketing";
            postergraduate[3] = "Foundation Of Marcketing";
            postergraduate[4] = "Managerial Skills";
        }else if(reg.equalsIgnoreCase("PB21")){
            postergraduate[0] = "Management resource Management";
            postergraduate[1] = "Operation Management";
            postergraduate[2] = "Organizational Behaviour";
            postergraduate[3] = "Organizational Behaviour";
            postergraduate[4] = "Business Policy";
        }else if(reg.equalsIgnoreCase("PB22")){
            postergraduate[0] = "Project Management";
            postergraduate[1] = "Stregic management";
            postergraduate[2] = "International Business";
            postergraduate[3] = "Supply chain management";
            postergraduate[4] = "Project Work";
        }else if(reg.equalsIgnoreCase("PB31")){
            postergraduate[0] = "Environment Studies";
            postergraduate[1] = "Supply chain management";
            postergraduate[2] = "Project Work";
            postergraduate[3] = "Business Law";
            postergraduate[4] = "Economics";
        }else if(reg.equalsIgnoreCase("PB32")){
            postergraduate[0] = "Microeconomics";
            postergraduate[1] = "Organizational Behaviour";
            postergraduate[2] = "Business Policy";
            postergraduate[3] = "Finance";
            postergraduate[4] = "Human Resource Management";
        }else if(reg.equalsIgnoreCase("PB41")){
            postergraduate[0] = "Business Research";
            postergraduate[1] = "Foundation Of Marcketing";
            postergraduate[2] = "Managerial Skills";
            postergraduate[3] = "Management resource Management";
            postergraduate[4] = "Operation Management";
        }else if(reg.equalsIgnoreCase("PB42")){
            postergraduate[0] = "Online Advertising";
            postergraduate[1] = "Strategic Thinking";
            postergraduate[2] = "Labour Economics";
            postergraduate[3] = "Project Management";
            postergraduate[4] = "Stregic management";
        }else if(reg.equalsIgnoreCase("PE11")){
            postergraduate[0] = "Physics";
            postergraduate[1] = "Computer Programming";
            postergraduate[2] = "Calcules";
            postergraduate[3] = "Control Enginearing";
            postergraduate[4] = "Electrical Enginearing";
        }else if(reg.equalsIgnoreCase("PE12")){
            postergraduate[0] = "Enginearing Graphics";
            postergraduate[1] = "Differential Equations";
            postergraduate[2] = "Kinematics";
            postergraduate[3] = "Plant Design";
            postergraduate[4] = "Drafting";
        }else if(reg.equalsIgnoreCase("PE21")){
            postergraduate[0] = "Chemistry";
            postergraduate[1] = "English Communication";
            postergraduate[2] = "Linear Algebra";
            postergraduate[3] = "Fluid Mechanics";
            postergraduate[4] = "Electronics";
        }else if(reg.equalsIgnoreCase("PE22")){
            postergraduate[0] = "Ethics & Value";
            postergraduate[1] = "Economics For Engineers";
            postergraduate[2] = "Kinematics";
            postergraduate[3] = "Heat And Mass";
            postergraduate[4] = "Computer Aided Design";
        }else if(reg.equalsIgnoreCase("PE31")){
            postergraduate[0] = "Material Technology";
            postergraduate[1] = "Fluid Mechanics";
            postergraduate[2] = "Electronics";
            postergraduate[3] = "Physics";
            postergraduate[4] = "Computer Programming";
        }else if(reg.equalsIgnoreCase("PE32")){
            postergraduate[0] = "Control Enginearing";
            postergraduate[1] = "Heat And Mass";
            postergraduate[2] = "Computer Aided Design";
            postergraduate[3] = "Enginearing Graphics";
            postergraduate[4] = "Differential Equations";
        }else if(reg.equalsIgnoreCase("PE41")){
            postergraduate[0] = "Chemical reactions";
            postergraduate[1] = "Plant Design";
            postergraduate[2] = "Drafting";
            postergraduate[3] = "Chemistry";
            postergraduate[4] = "English Communication";
        }else if(reg.equalsIgnoreCase("PE42")){
            postergraduate[0] = "Robotics";
            postergraduate[1] = "Control Enginearing";
            postergraduate[2] = "Electrical Enginearing";
            postergraduate[3] = "Enginearing Graphics";
            postergraduate[4] = "Differential Equations";
        }
        
        return postergraduate;
    }
   
     
     
     public String[] getPostergraduateCourse3(String reg) {
        String[] postergraduate = new String[30];
        if (reg.equalsIgnoreCase("PC11")) {
            postergraduate[0] = "ICT Tools";
            postergraduate[1] = "Computer Architecture";
            postergraduate[2] = "Communication Skills";
            postergraduate[3] = "Java";
            postergraduate[4] = "Python";
        }else if(reg.equalsIgnoreCase("PC12")){
            postergraduate[0] = "Data Structure & Algorithms";
            postergraduate[1] = "Artificial Intelligence";
            postergraduate[2] = "Computer Security";
            postergraduate[3] = "Mathamatical method";
            postergraduate[4] = "Statistic";
        }else if(reg.equalsIgnoreCase("PC21")){
            postergraduate[0] = "Compiler Design";
            postergraduate[1] = "Cloud Computing";
            postergraduate[2] = "Real Time Systems";
            postergraduate[3] = "Cysber Security";
            postergraduate[4] = "Computer Security";
        }else if(reg.equalsIgnoreCase("PC22")){
            postergraduate[0] = "Web Design";
            postergraduate[1] = "Mahine Learning";
            postergraduate[2] = "Modern Database";
            postergraduate[3] = "Wireless Sensor Network";
            postergraduate[4] = "Data Mining";
        }else if(reg.equalsIgnoreCase("PC31")){
            postergraduate[0] = "Software Testing";
            postergraduate[1] = "Wireless Sensor Network";
            postergraduate[2] = "Data Mining";
            postergraduate[3] = "Web Design";
            postergraduate[4] = "Mahine Learning";
        }else if(reg.equalsIgnoreCase("PC32")){
            postergraduate[0] = "Distributed Systems";
            postergraduate[1] = "Cysber Security";
            postergraduate[2] = "Computer Security";
            postergraduate[3] = "Compiler Design";
            postergraduate[4] = "Cloud Computing";
        }else if(reg.equalsIgnoreCase("PC41")){
            postergraduate[0] = "Research Methodology";
            postergraduate[1] = "Mathamatical method";
            postergraduate[2] = "Statistic";
            postergraduate[3] = "ICT Tools";
            postergraduate[4] = "Computer Architecture";
        }else if(reg.equalsIgnoreCase("PC42")){
            postergraduate[0] = "Discrete Maths";
            postergraduate[1] = "Java";
            postergraduate[2] = "Python";
            postergraduate[3] = "Artificial Intelligence";
            postergraduate[4] = "Computer Security";
        }else if(reg.equalsIgnoreCase("PB11")){
            postergraduate[0] = "Business Law";
            postergraduate[1] = "Economics";
            postergraduate[2] = "Ethics";
            postergraduate[3] = "Strategic Thinking";
            postergraduate[4] = "Labour Economics";
        }else if(reg.equalsIgnoreCase("PB12")){
            postergraduate[0] = "Finance";
            postergraduate[1] = "Human Resource Management";
            postergraduate[2] = "Marketing";
            postergraduate[3] = "Foundation Of Marcketing";
            postergraduate[4] = "Managerial Skills";
        }else if(reg.equalsIgnoreCase("PB21")){
            postergraduate[0] = "Management resource Management";
            postergraduate[1] = "Operation Management";
            postergraduate[2] = "Organizational Behaviour";
            postergraduate[3] = "Organizational Behaviour";
            postergraduate[4] = "Business Policy";
        }else if(reg.equalsIgnoreCase("PB22")){
            postergraduate[0] = "Project Management";
            postergraduate[1] = "Stregic management";
            postergraduate[2] = "International Business";
            postergraduate[3] = "Supply chain management";
            postergraduate[4] = "Project Work";
        }else if(reg.equalsIgnoreCase("PB31")){
            postergraduate[0] = "Environment Studies";
            postergraduate[1] = "Supply chain management";
            postergraduate[2] = "Project Work";
            postergraduate[3] = "Business Law";
            postergraduate[4] = "Economics";
        }else if(reg.equalsIgnoreCase("PB32")){
            postergraduate[0] = "Microeconomics";
            postergraduate[1] = "Organizational Behaviour";
            postergraduate[2] = "Business Policy";
            postergraduate[3] = "Finance";
            postergraduate[4] = "Human Resource Management";
        }else if(reg.equalsIgnoreCase("PB41")){
            postergraduate[0] = "Business Research";
            postergraduate[1] = "Foundation Of Marcketing";
            postergraduate[2] = "Managerial Skills";
            postergraduate[3] = "Management resource Management";
            postergraduate[4] = "Operation Management";
        }else if(reg.equalsIgnoreCase("PB42")){
            postergraduate[0] = "Online Advertising";
            postergraduate[1] = "Strategic Thinking";
            postergraduate[2] = "Labour Economics";
            postergraduate[3] = "Project Management";
            postergraduate[4] = "Stregic management";
        }else if(reg.equalsIgnoreCase("PE11")){
            postergraduate[0] = "Physics";
            postergraduate[1] = "Computer Programming";
            postergraduate[2] = "Calcules";
            postergraduate[3] = "Control Enginearing";
            postergraduate[4] = "Electrical Enginearing";
        }else if(reg.equalsIgnoreCase("PE12")){
            postergraduate[0] = "Enginearing Graphics";
            postergraduate[1] = "Differential Equations";
            postergraduate[2] = "Kinematics";
            postergraduate[3] = "Plant Design";
            postergraduate[4] = "Drafting";
        }else if(reg.equalsIgnoreCase("PE21")){
            postergraduate[0] = "Chemistry";
            postergraduate[1] = "English Communication";
            postergraduate[2] = "Linear Algebra";
            postergraduate[3] = "Fluid Mechanics";
            postergraduate[4] = "Electronics";
        }else if(reg.equalsIgnoreCase("PE22")){
            postergraduate[0] = "Ethics & Value";
            postergraduate[1] = "Economics For Engineers";
            postergraduate[2] = "Kinematics";
            postergraduate[3] = "Heat And Mass";
            postergraduate[4] = "Computer Aided Design";
        }else if(reg.equalsIgnoreCase("PE31")){
            postergraduate[0] = "Material Technology";
            postergraduate[1] = "Fluid Mechanics";
            postergraduate[2] = "Electronics";
            postergraduate[3] = "Physics";
            postergraduate[4] = "Computer Programming";
        }else if(reg.equalsIgnoreCase("PE32")){
            postergraduate[0] = "Control Enginearing";
            postergraduate[1] = "Heat And Mass";
            postergraduate[2] = "Computer Aided Design";
            postergraduate[3] = "Enginearing Graphics";
            postergraduate[4] = "Differential Equations";
        }else if(reg.equalsIgnoreCase("PE41")){
            postergraduate[0] = "Chemical reactions";
            postergraduate[1] = "Plant Design";
            postergraduate[2] = "Drafting";
            postergraduate[3] = "Chemistry";
            postergraduate[4] = "English Communication";
        }else if(reg.equalsIgnoreCase("PE42")){
            postergraduate[0] = "Robotics";
            postergraduate[1] = "Control Enginearing";
            postergraduate[2] = "Electrical Enginearing";
            postergraduate[3] = "Enginearing Graphics";
            postergraduate[4] = "Differential Equations";
        }
        
        return postergraduate;
    }
   
     
     
     public String[] getPostergraduateCourse4(String reg) {
        String[] postergraduate = new String[30];
        if (reg.equalsIgnoreCase("PC11")) {
            postergraduate[0] = "ICT Tools";
            postergraduate[1] = "Computer Architecture";
            postergraduate[2] = "Communication Skills";
            postergraduate[3] = "Java";
            postergraduate[4] = "Python";
        }else if(reg.equalsIgnoreCase("PC12")){
            postergraduate[0] = "Data Structure & Algorithms";
            postergraduate[1] = "Artificial Intelligence";
            postergraduate[2] = "Computer Security";
            postergraduate[3] = "Mathamatical method";
            postergraduate[4] = "Statistic";
        }else if(reg.equalsIgnoreCase("PC21")){
            postergraduate[0] = "Compiler Design";
            postergraduate[1] = "Cloud Computing";
            postergraduate[2] = "Real Time Systems";
            postergraduate[3] = "Cysber Security";
            postergraduate[4] = "Computer Security";
        }else if(reg.equalsIgnoreCase("PC22")){
            postergraduate[0] = "Web Design";
            postergraduate[1] = "Mahine Learning";
            postergraduate[2] = "Modern Database";
            postergraduate[3] = "Wireless Sensor Network";
            postergraduate[4] = "Data Mining";
        }else if(reg.equalsIgnoreCase("PC31")){
            postergraduate[0] = "Software Testing";
            postergraduate[1] = "Wireless Sensor Network";
            postergraduate[2] = "Data Mining";
            postergraduate[3] = "Web Design";
            postergraduate[4] = "Mahine Learning";
        }else if(reg.equalsIgnoreCase("PC32")){
            postergraduate[0] = "Distributed Systems";
            postergraduate[1] = "Cysber Security";
            postergraduate[2] = "Computer Security";
            postergraduate[3] = "Compiler Design";
            postergraduate[4] = "Cloud Computing";
        }else if(reg.equalsIgnoreCase("PC41")){
            postergraduate[0] = "Research Methodology";
            postergraduate[1] = "Mathamatical method";
            postergraduate[2] = "Statistic";
            postergraduate[3] = "ICT Tools";
            postergraduate[4] = "Computer Architecture";
        }else if(reg.equalsIgnoreCase("PC42")){
            postergraduate[0] = "Discrete Maths";
            postergraduate[1] = "Java";
            postergraduate[2] = "Python";
            postergraduate[3] = "Artificial Intelligence";
            postergraduate[4] = "Computer Security";
        }else if(reg.equalsIgnoreCase("PB11")){
            postergraduate[0] = "Business Law";
            postergraduate[1] = "Economics";
            postergraduate[2] = "Ethics";
            postergraduate[3] = "Strategic Thinking";
            postergraduate[4] = "Labour Economics";
        }else if(reg.equalsIgnoreCase("PB12")){
            postergraduate[0] = "Finance";
            postergraduate[1] = "Human Resource Management";
            postergraduate[2] = "Marketing";
            postergraduate[3] = "Foundation Of Marcketing";
            postergraduate[4] = "Managerial Skills";
        }else if(reg.equalsIgnoreCase("PB21")){
            postergraduate[0] = "Management resource Management";
            postergraduate[1] = "Operation Management";
            postergraduate[2] = "Organizational Behaviour";
            postergraduate[3] = "Organizational Behaviour";
            postergraduate[4] = "Business Policy";
        }else if(reg.equalsIgnoreCase("PB22")){
            postergraduate[0] = "Project Management";
            postergraduate[1] = "Stregic management";
            postergraduate[2] = "International Business";
            postergraduate[3] = "Supply chain management";
            postergraduate[4] = "Project Work";
        }else if(reg.equalsIgnoreCase("PB31")){
            postergraduate[0] = "Environment Studies";
            postergraduate[1] = "Supply chain management";
            postergraduate[2] = "Project Work";
            postergraduate[3] = "Business Law";
            postergraduate[4] = "Economics";
        }else if(reg.equalsIgnoreCase("PB32")){
            postergraduate[0] = "Microeconomics";
            postergraduate[1] = "Organizational Behaviour";
            postergraduate[2] = "Business Policy";
            postergraduate[3] = "Finance";
            postergraduate[4] = "Human Resource Management";
        }else if(reg.equalsIgnoreCase("PB41")){
            postergraduate[0] = "Business Research";
            postergraduate[1] = "Foundation Of Marcketing";
            postergraduate[2] = "Managerial Skills";
            postergraduate[3] = "Management resource Management";
            postergraduate[4] = "Operation Management";
        }else if(reg.equalsIgnoreCase("PB42")){
            postergraduate[0] = "Online Advertising";
            postergraduate[1] = "Strategic Thinking";
            postergraduate[2] = "Labour Economics";
            postergraduate[3] = "Project Management";
            postergraduate[4] = "Stregic management";
        }else if(reg.equalsIgnoreCase("PE11")){
            postergraduate[0] = "Physics";
            postergraduate[1] = "Computer Programming";
            postergraduate[2] = "Calcules";
            postergraduate[3] = "Control Enginearing";
            postergraduate[4] = "Electrical Enginearing";
        }else if(reg.equalsIgnoreCase("PE12")){
            postergraduate[0] = "Enginearing Graphics";
            postergraduate[1] = "Differential Equations";
            postergraduate[2] = "Kinematics";
            postergraduate[3] = "Plant Design";
            postergraduate[4] = "Drafting";
        }else if(reg.equalsIgnoreCase("PE21")){
            postergraduate[0] = "Chemistry";
            postergraduate[1] = "English Communication";
            postergraduate[2] = "Linear Algebra";
            postergraduate[3] = "Fluid Mechanics";
            postergraduate[4] = "Electronics";
        }else if(reg.equalsIgnoreCase("PE22")){
            postergraduate[0] = "Ethics & Value";
            postergraduate[1] = "Economics For Engineers";
            postergraduate[2] = "Kinematics";
            postergraduate[3] = "Heat And Mass";
            postergraduate[4] = "Computer Aided Design";
        }else if(reg.equalsIgnoreCase("PE31")){
            postergraduate[0] = "Material Technology";
            postergraduate[1] = "Fluid Mechanics";
            postergraduate[2] = "Electronics";
            postergraduate[3] = "Physics";
            postergraduate[4] = "Computer Programming";
        }else if(reg.equalsIgnoreCase("PE32")){
            postergraduate[0] = "Control Enginearing";
            postergraduate[1] = "Heat And Mass";
            postergraduate[2] = "Computer Aided Design";
            postergraduate[3] = "Enginearing Graphics";
            postergraduate[4] = "Differential Equations";
        }else if(reg.equalsIgnoreCase("PE41")){
            postergraduate[0] = "Chemical reactions";
            postergraduate[1] = "Plant Design";
            postergraduate[2] = "Drafting";
            postergraduate[3] = "Chemistry";
            postergraduate[4] = "English Communication";
        }else if(reg.equalsIgnoreCase("PE42")){
            postergraduate[0] = "Robotics";
            postergraduate[1] = "Control Enginearing";
            postergraduate[2] = "Electrical Enginearing";
            postergraduate[3] = "Enginearing Graphics";
            postergraduate[4] = "Differential Equations";
        }
        
        return postergraduate;
     }
    private void ddcourseidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddcourseidItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.ddcourseid.getSelectedIndex() > 0) {
                this.ddsubject1.setModel(new DefaultComboBoxModel(this.getPostergraduateCourse1(this.ddcourseid.getSelectedItem().toString())));
            }
        }
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.ddcourseid.getSelectedIndex() > 0) {
                this.ddsubject2.setModel(new DefaultComboBoxModel(this.getPostergraduateCourse2(this.ddcourseid.getSelectedItem().toString())));
            }
        }
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.ddcourseid.getSelectedIndex() > 0) {
                this.ddsubject3.setModel(new DefaultComboBoxModel(this.getPostergraduateCourse3(this.ddcourseid.getSelectedItem().toString())));
            }
        }
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.ddcourseid.getSelectedIndex() > 0) {
                this.ddsubject4.setModel(new DefaultComboBoxModel(this.getPostergraduateCourse4(this.ddcourseid.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ddcourseidItemStateChanged

    private void ddcourseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddcourseidActionPerformed
        if (ddcourseid.getSelectedItem().toString() == "UC11") {
            txtm1.setText("Software Enginearing ");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC11") {
            txtm2.setText("Data Structure and Algorithm");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC12") {
            txtm1.setText("Computer System");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC12") {
            txtm2.setText("Data Base");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC21") {
            txtm1.setText("Discrete Maths");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC21") {
            txtm2.setText("Mathamatical Methods");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC22") {
            txtm1.setText("Networking");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC22") {
            txtm2.setText("Statistics");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC31") {
            txtm1.setText("Java");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC31") {
            txtm2.setText("C/C++");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC32") {
            txtm1.setText("Python");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC32") {
            txtm2.setText("Scala");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC41") {
            txtm1.setText("PHP");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC41") {
            txtm2.setText("Cyber Security");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtm1.setText("Artificial Inteligent");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtm2.setText("Racket");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB11") {
            txtm1.setText("Law");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB11") {
            txtm2.setText("Economics");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB12") {
            txtm1.setText("Mathematics");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB12") {
            txtm2.setText("E Commerce");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB21") {
            txtm1.setText("Auditing");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB21") {
            txtm2.setText("Financial Plan");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB22") {
            txtm1.setText("Invesment Analysis");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB22") {
            txtm2.setText("Human Resourse Managemenet ");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB31") {
            txtm1.setText("Financial Account");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB31") {
            txtm2.setText("Cooperative Finance");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB32") {
            txtm1.setText("Statistics");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB32") {
            txtm2.setText("Global Marketing");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB41") {
            txtm1.setText("Customer Behaviour");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB41") {
            txtm2.setText("Taxation");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB42") {
            txtm1.setText("IT Risk Management");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB42") {
            txtm2.setText("Managemenet Of Change");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE11") {
            txtm1.setText("Linear Algebra");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE11") {
            txtm2.setText("Environmental Studies");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE12") {
            txtm1.setText("Physics");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE12") {
            txtm2.setText("Chemistry");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE21") {
            txtm1.setText("Enginearing Graphycs");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE21") {
            txtm2.setText("Ethics & Values");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE22") {
            txtm1.setText("Community Service");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE22") {
            txtm2.setText("Electrical Enginearing");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE31") {
            txtm1.setText("ICT Tools");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE31") {
            txtm2.setText("Fluid Mechanics");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE32") {
            txtm1.setText("Fractions");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE32") {
            txtm2.setText("Heat and Mass");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE41") {
            txtm1.setText("Power Planet");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE41") {
            txtm2.setText("Control Enginearing");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE42") {
            txtm1.setText("Dynamics");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE42") {
            txtm2.setText("Chemical Engnearing");
        }

        /**
        * *****************************subject
        * code*********************************************************
        */
        if (ddcourseid.getSelectedItem().toString() == "UC11") {
            txtsubc1.setText("SCS 1000");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC11") {
            txtsubc2.setText("SCS 1001");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC11") {
            txtsubc3.setText("SCS 1002");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC11") {
            txtsubc4.setText("SCS 1003");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC11") {
            txtsubc5.setText("SCS 1004");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC11") {
            txtsubc6.setText("SCS 1005");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC12") {
            txtsubc1.setText("SCS 1006");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC12") {
            txtsubc2.setText("SCS 1007");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC12") {
            txtsubc3.setText("SCS 1008");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC12") {
            txtsubc4.setText("SCS 1009");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC12") {
            txtsubc5.setText("SCS 1010");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC12") {
            txtsubc6.setText("SCS 1011");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC21") {
            txtsubc1.setText("SCS 1012");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC21") {
            txtsubc2.setText("SCS 1013");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC21") {
            txtsubc3.setText("SCS 1014");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC21") {
            txtsubc4.setText("SCS 1015");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC21") {
            txtsubc5.setText("SCS 1016");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC21") {
            txtsubc6.setText("SCS 1017");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC22") {
            txtsubc1.setText("SCS 1018");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC22") {
            txtsubc2.setText("SCS 1019");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC22") {
            txtsubc3.setText("SCS 1020");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC22") {
            txtsubc4.setText("SCS 1021");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC22") {
            txtsubc5.setText("SCS 1022");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC22") {
            txtsubc6.setText("SCS 1023");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC31") {
            txtsubc1.setText("SCS 1024");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC31") {
            txtsubc2.setText("SCS 1025");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC31") {
            txtsubc3.setText("SCS 1026");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC31") {
            txtsubc4.setText("SCS 1027");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC31") {
            txtsubc5.setText("SCS 1028");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC31") {
            txtsubc6.setText("SCS 1029");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC32") {
            txtsubc1.setText("SCS 1030");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC32") {
            txtsubc2.setText("SCS 1031");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC32") {
            txtsubc3.setText("SCS 1032");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC32") {
            txtsubc4.setText("SCS 1033");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC32") {
            txtsubc5.setText("SCS 1034");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC32") {
            txtsubc6.setText("SCS 1035");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC41") {
            txtsubc1.setText("SCS 1036");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC41") {
            txtsubc2.setText("SCS 1037");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC41") {
            txtsubc3.setText("SCS 1038");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC41") {
            txtsubc4.setText("SCS 1039");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC41") {
            txtsubc5.setText("SCS 1040");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtsubc1.setText("SCS 1041");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtsubc2.setText("SCS 1042");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtsubc3.setText("SCS 1043");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtsubc4.setText("SCS 1044");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtsubc5.setText("SCS 1045");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtsubc6.setText("SCS 1046");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB11") {
            txtsubc1.setText("SCS 1047");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB11") {
            txtsubc2.setText("SCS 1048");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB11") {
            txtsubc3.setText("SCS 1049");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB11") {
            txtsubc4.setText("SCS 1050");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB11") {
            txtsubc5.setText("SCS 1051");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB11") {
            txtsubc6.setText("SCS 1052");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB12") {
            txtsubc1.setText("SCS 1053");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB12") {
            txtsubc2.setText("SCS 1054");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB12") {
            txtsubc3.setText("SCS 1055");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB12") {
            txtsubc4.setText("SCS 1056");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB12") {
            txtsubc5.setText("SCS 1057");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB12") {
            txtsubc6.setText("SCS 1058");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB21") {
            txtsubc1.setText("SCS 1059");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB21") {
            txtsubc2.setText("SCS 1060");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB21") {
            txtsubc3.setText("SCS 1061");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB21") {
            txtsubc4.setText("SCS 1062");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB21") {
            txtsubc5.setText("SCS 1063");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB21") {
            txtsubc6.setText("SCS 1064");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB22") {
            txtsubc1.setText("SCS 1065");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB22") {
            txtsubc2.setText("SCS 1066");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB22") {
            txtsubc3.setText("SCS 1067");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB22") {
            txtsubc4.setText("SCS 1068");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB22") {
            txtsubc5.setText("SCS 1069");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB22") {
            txtsubc6.setText("SCS 1070");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB31") {
            txtsubc1.setText("SCS 1071");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB31") {
            txtsubc2.setText("SCS 1072");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB31") {
            txtsubc3.setText("SCS 1073");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB31") {
            txtsubc4.setText("SCS 1074");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB31") {
            txtsubc5.setText("SCS 1075");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB31") {
            txtsubc6.setText("SCS 1076");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB32") {
            txtsubc1.setText("SCS 1077");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB32") {
            txtsubc2.setText("SCS 1078");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB32") {
            txtsubc3.setText("SCS 1079");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB32") {
            txtsubc4.setText("SCS 1080");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB32") {
            txtsubc5.setText("SCS 1081");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB32") {
            txtsubc6.setText("SCS 1082");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB41") {
            txtsubc1.setText("SCS 1083");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB41") {
            txtsubc2.setText("SCS 1084");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB41") {
            txtsubc3.setText("SCS 1085");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB41") {
            txtsubc4.setText("SCS 1086");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB41") {
            txtsubc5.setText("SCS 1087");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB41") {
            txtsubc6.setText("SCS 1088");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB42") {
            txtsubc1.setText("SCS 1089");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB42") {
            txtsubc2.setText("SCS 1090");
        }
        if (ddcourseid.getSelectedItem().toString() == "UC42") {
            txtsubc3.setText("SCS 1091");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB42") {
            txtsubc4.setText("SCS 1092");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB42") {
            txtsubc5.setText("SCS 1093");
        }
        if (ddcourseid.getSelectedItem().toString() == "UB42") {
            txtsubc6.setText("SCS 1094");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE11") {
            txtsubc1.setText("SCS 1095");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE11") {
            txtsubc2.setText("SCS 1096");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE11") {
            txtsubc3.setText("SCS 1097");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE11") {
            txtsubc4.setText("SCS 1098");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE11") {
            txtsubc5.setText("SCS 1099");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE11") {
            txtsubc6.setText("SCS 1100");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE12") {
            txtsubc1.setText("SCS 1101");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE12") {
            txtsubc2.setText("SCS 1102");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE12") {
            txtsubc3.setText("SCS 1103");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE12") {
            txtsubc4.setText("SCS 1104");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE12") {
            txtsubc5.setText("SCS 1105");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE12") {
            txtsubc6.setText("SCS 1106");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE21") {
            txtsubc1.setText("SCS 1107");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE21") {
            txtsubc2.setText("SCS 1108");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE21") {
            txtsubc3.setText("SCS 1109");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE21") {
            txtsubc4.setText("SCS 1110");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE21") {
            txtsubc5.setText("SCS 1111");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE21") {
            txtsubc6.setText("SCS 1112");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE22") {
            txtsubc1.setText("SCS 1113");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE22") {
            txtsubc2.setText("SCS 1114");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE22") {
            txtsubc3.setText("SCS 1115");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE22") {
            txtsubc4.setText("SCS 1116");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE22") {
            txtsubc5.setText("SCS 1117");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE22") {
            txtsubc6.setText("SCS 1118");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE31") {
            txtsubc1.setText("SCS 1119");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE31") {
            txtsubc2.setText("SCS 1120");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE31") {
            txtsubc3.setText("SCS 1121");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE31") {
            txtsubc4.setText("SCS 1122");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE31") {
            txtsubc5.setText("SCS 1123");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE31") {
            txtsubc6.setText("SCS 1124");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE32") {
            txtsubc1.setText("SCS 1125");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE32") {
            txtsubc2.setText("SCS 1126");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE32") {
            txtsubc3.setText("SCS 1127");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE32") {
            txtsubc4.setText("SCS 1128");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE32") {
            txtsubc5.setText("SCS 1129");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE32") {
            txtsubc6.setText("SCS 1130");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE41") {
            txtsubc1.setText("SCS 1131");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE41") {
            txtsubc2.setText("SCS 1132");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE41") {
            txtsubc3.setText("SCS 1133");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE41") {
            txtsubc4.setText("SCS 1134");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE41") {
            txtsubc5.setText("SCS 1135");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE41") {
            txtsubc6.setText("SCS 1136");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE42") {
            txtsubc1.setText("SCS 1137");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE42") {
            txtsubc2.setText("SCS 1138");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE42") {
            txtsubc3.setText("SCS 1139");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE42") {
            txtsubc4.setText("SCS 1140");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE42") {
            txtsubc5.setText("SCS 1141");
        }
        if (ddcourseid.getSelectedItem().toString() == "UE42") {
            txtsubc6.setText("SCS 1142");
        }
    }//GEN-LAST:event_ddcourseidActionPerformed

    private void btnproceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproceedActionPerformed
        PostergraduateStudentsCourseRegDetails posd = new PostergraduateStudentsCourseRegDetails();

        posd.setStudentID(txtstudentid.getText());                              //get the we entered text feilds details and fill(set) them in to UndergraduateStudentDetails object
        posd.setFaculty(ddfaculty.getSelectedItem().toString());
        posd.setYearOfReg(Integer.parseInt(ddyearofregistration.getSelectedItem().toString()));
        posd.setCourseID(ddcourseid.getSelectedItem().toString());
        posd.setMainsub1(txtm1.getText());
        posd.setMainsubID1(txtsubc1.getText());
        posd.setMainsub1Payment(Integer.parseInt(txtp1.getText().toString()));
        posd.setMainsub2(txtm2.getText());
        posd.setMainsubID2(txtsubc2.getText());
        posd.setMainsub2Payment(Integer.parseInt(txtp2.getText().toString()));
        posd.setChoosesub1(ddsubject1.getSelectedItem().toString());
        posd.setChoosesubID1(txtsubc3.getText());
        posd.setChoosesub1Payment(Integer.parseInt(txtp3.getText().toString()));
        posd.setChoosesub2(ddsubject2.getSelectedItem().toString());
        posd.setChoosesubID2(txtsubc4.getText());
        posd.setChoosesub2Payment(Integer.parseInt(txtp4.getText().toString()));
        posd.setChoosesub3(ddsubject3.getSelectedItem().toString());
        posd.setChoosesubID3(txtsubc5.getText());
        posd.setChoosesub3Payment(Integer.parseInt(txtp5.getText().toString()));
        posd.setChoosesub4(ddsubject4.getSelectedItem().toString());
        posd.setChoosesubID4(txtsubc6.getText());
        posd.setChoosesub4Payment(Integer.parseInt(txtp6.getText().toString()));

        boolean result = DBop.updatePostergraduateCourse(posd);  // parse add UndergraduateStudentDetails to add employee method
        // addundergraduatestudentdetails method return true or false.result get that

        if (result) {
            JOptionPane.showMessageDialog(this, "Successfully inserted !");

            
        } else {
            JOptionPane.showMessageDialog(this, "OOPS Error Occured While Inserting");

        }
    }//GEN-LAST:event_btnproceedActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        PostergraduateCourses o = new PostergraduateCourses();
        o.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void ddfacultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddfacultyItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.ddfaculty.getSelectedIndex() > 0) {
                this.ddcourseid.setModel(new DefaultComboBoxModel(this.getCourseID(this.ddfaculty.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ddfacultyItemStateChanged

    private void ddfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddfacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddfacultyActionPerformed

    private void txtsubc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubc2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostergraduateStudentsCourseUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostergraduateStudentsCourseUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostergraduateStudentsCourseUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostergraduateStudentsCourseUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostergraduateStudentsCourseUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnproceed;
    private javax.swing.JComboBox<String> ddcourseid;
    private javax.swing.JComboBox<String> ddfaculty;
    private javax.swing.JComboBox<String> ddsubject1;
    private javax.swing.JComboBox<String> ddsubject2;
    private javax.swing.JComboBox<String> ddsubject3;
    private javax.swing.JComboBox<String> ddsubject4;
    private javax.swing.JComboBox<String> ddyearofregistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtm1;
    private javax.swing.JTextField txtm2;
    private javax.swing.JTextField txtp1;
    private javax.swing.JTextField txtp2;
    private javax.swing.JTextField txtp3;
    private javax.swing.JTextField txtp4;
    private javax.swing.JTextField txtp5;
    private javax.swing.JTextField txtp6;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtsubc1;
    private javax.swing.JTextField txtsubc2;
    private javax.swing.JTextField txtsubc3;
    private javax.swing.JTextField txtsubc4;
    private javax.swing.JTextField txtsubc5;
    private javax.swing.JTextField txtsubc6;
    // End of variables declaration//GEN-END:variables
}
